// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxjzlhnzmxpwptzjbhur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4anpsaG56bXhwd3B0empiaHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNDA5OTksImV4cCI6MjA1NTkxNjk5OX0.h6HFSqzOf3EcMw_HwqC15m-9uxySzoD7iG9cSQKuOM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);